/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import view.Paineis.CambiaPanel;
import view.Paineis.Painel_Cadastros;
import view.Paineis.Painel_Home;

/**
 *
 * @author Antonio Joao Zimila
 */
public class Janela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Janela_Principal
     */
    public Janela_Principal() {
        initComponents();
     this.setLocationRelativeTo(this);
     this.opcao_um.setSelected(true);
    
     /*PainelCasa recebe todos os pais que criei
       painel Home é o primeiro painel que entra no painelCasa
     */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botaoMenuPr = new javax.swing.JButton();
        panl1Menu = new javax.swing.JPanel();
        opcao_um = new BotaoMenu.RSButtonMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        opcao_dois = new BotaoMenu.RSButtonMetro();
        opcao_tres = new BotaoMenu.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        PainelCasa = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(38, 86, 186));
        jPanel1.setPreferredSize(new java.awt.Dimension(964, 63));

        botaoMenuPr.setBackground(new java.awt.Color(38, 86, 186));
        botaoMenuPr.setForeground(new java.awt.Color(38, 86, 186));
        botaoMenuPr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/menu.png"))); // NOI18N
        botaoMenuPr.setBorder(null);
        botaoMenuPr.setContentAreaFilled(false);
        botaoMenuPr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMenuPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuPrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoMenuPr, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1052, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoMenuPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1042;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        jPanel4.add(jPanel1, gridBagConstraints);

        opcao_um.setBackground(new java.awt.Color(204, 204, 204));
        opcao_um.setForeground(new java.awt.Color(128, 128, 131));
        opcao_um.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home.png"))); // NOI18N
        opcao_um.setText("HOME");
        opcao_um.setToolTipText("");
        opcao_um.setColorHover(new java.awt.Color(204, 204, 204));
        opcao_um.setColorNormal(new java.awt.Color(204, 204, 204));
        opcao_um.setColorTextHover(new java.awt.Color(128, 128, 131));
        opcao_um.setColorTextNormal(new java.awt.Color(128, 128, 131));
        opcao_um.setColorTextPressed(new java.awt.Color(128, 128, 131));
        opcao_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao_umActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(239, 238, 244));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 128, 131));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTUDANTES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        opcao_dois.setBackground(new java.awt.Color(239, 238, 244));
        opcao_dois.setForeground(new java.awt.Color(128, 128, 131));
        opcao_dois.setText("CADASTRAR+");
        opcao_dois.setColorHover(new java.awt.Color(204, 204, 204));
        opcao_dois.setColorNormal(new java.awt.Color(239, 238, 244));
        opcao_dois.setColorPressed(new java.awt.Color(239, 238, 244));
        opcao_dois.setColorTextHover(new java.awt.Color(128, 128, 131));
        opcao_dois.setColorTextNormal(new java.awt.Color(128, 128, 131));
        opcao_dois.setColorTextPressed(new java.awt.Color(128, 128, 131));
        opcao_dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao_doisActionPerformed(evt);
            }
        });

        opcao_tres.setForeground(new java.awt.Color(128, 128, 131));
        opcao_tres.setText("LISTAR");
        opcao_tres.setColorHover(new java.awt.Color(204, 204, 204));
        opcao_tres.setColorNormal(new java.awt.Color(239, 238, 244));
        opcao_tres.setColorTextHover(new java.awt.Color(128, 128, 131));
        opcao_tres.setColorTextNormal(new java.awt.Color(128, 128, 131));
        opcao_tres.setColorTextPressed(new java.awt.Color(128, 128, 131));
        opcao_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao_tresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panl1MenuLayout = new javax.swing.GroupLayout(panl1Menu);
        panl1Menu.setLayout(panl1MenuLayout);
        panl1MenuLayout.setHorizontalGroup(
            panl1MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(opcao_um, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(opcao_dois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panl1MenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(opcao_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panl1MenuLayout.setVerticalGroup(
            panl1MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panl1MenuLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(opcao_um, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcao_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(opcao_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 350;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(panl1Menu, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(jPanel5, gridBagConstraints);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(jPanel6, gridBagConstraints);

        PainelCasa.setBackground(new java.awt.Color(255, 255, 255));
        PainelCasa.setName(""); // NOI18N
        PainelCasa.setLayout(new javax.swing.BoxLayout(PainelCasa, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 950;
        gridBagConstraints.ipady = 620;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(PainelCasa, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcao_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao_umActionPerformed
        new CambiaPanel(PainelCasa,new Painel_Home());
        if(this.opcao_um.isSelected()){
      
        this.opcao_um.setColorNormal(new Color(204,204,204));
        this.opcao_um.setColorHover(new Color(204,204,204));
        this.opcao_um.setColorPressed(new Color(0,0,0));    
        }else{
        this.opcao_um.setColorNormal(new Color(204,204,204));
        this.opcao_um.setColorHover(new Color(204,204,204));
        this.opcao_um.setColorPressed(new Color(0,0,0));   
        }
    }//GEN-LAST:event_opcao_umActionPerformed

    private void botaoMenuPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuPrActionPerformed
          int posicion = panl1Menu.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, panl1Menu);
        }else{
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, panl1Menu);
        }
    }//GEN-LAST:event_botaoMenuPrActionPerformed

    private void opcao_doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao_doisActionPerformed
        new CambiaPanel(PainelCasa,new Painel_Cadastros());
        if(this.opcao_dois.isSelected()){
       // new CambiaPanel(PainelCasa,new Painel_Cadastros());
        //new CambiaPanel(PainelCasa,new Painel_Home());
        this.opcao_dois.setColorNormal(new Color(239,238,244));
        this.opcao_dois.setColorHover(new Color(204,204,204));
        this.opcao_dois.setColorPressed(new Color(0,0,0));    
        }else{
        this.opcao_dois.setColorNormal(new Color(239,238,244));
        this.opcao_dois.setColorHover(new Color(204,204,204));
        this.opcao_dois.setColorPressed(new Color(0,0,0));       
       }
    }//GEN-LAST:event_opcao_doisActionPerformed

    private void opcao_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao_tresActionPerformed
        if(this.opcao_tres.isSelected()){
        //new CambiaPanel(PainelCasa,new Painel_Home());
        this.opcao_tres.setColorNormal(new Color(239,238,244));
        this.opcao_tres.setColorHover(new Color(204,204,204));
        this.opcao_tres.setColorPressed(new Color(0,0,0));    
        }else{
        this.opcao_tres.setColorNormal(new Color(239,238,244));
        this.opcao_tres.setColorHover(new Color(204,204,204));
        this.opcao_tres.setColorPressed(new Color(0,0,0));     
        }
    }//GEN-LAST:event_opcao_tresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCasa;
    private javax.swing.JButton botaoMenuPr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private BotaoMenu.RSButtonMetro opcao_dois;
    private BotaoMenu.RSButtonMetro opcao_tres;
    private BotaoMenu.RSButtonMetro opcao_um;
    private javax.swing.JPanel panl1Menu;
    // End of variables declaration//GEN-END:variables
}
